services:
  - type: web
    name: ciberseguridad-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_JWKS_URL
        sync: false
      - key: API_CORS_ORIGINS
        sync: false
